apiVersion: v1
kind: Service
metadata:
  name: '{{ .Name }}'
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: !!var app # variable reference
  template:
    metadata:
      labels:
        app: '{{ .Label }}' # templated reference
    spec:
      containers:
      - name: nginx
        image: my.private.repo/!!start Image !!end  # nested variable reference
        ports:
        - containerPort: 80
